<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-18EMREV" failures="1" tests="2" name="cucumberOptions.TestRunner" time="227.398" errors="0" timestamp="03 Jun 2019 11:35:11 GMT" skipped="0">
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="91.811">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at stepDefinitions.stepDefinitions.user_logs_in_and_gets_redirected(stepDefinitions.java:55)
at âœ½.User logs in(file:src/test/java/features/Login.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="cucumberOptions.TestRunner" name="runScenario" time="135.587"/>
</testsuite> <!-- cucumberOptions.TestRunner -->
