<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-08-03T09:54:08Z" name="Guru99 Testing" finished-at="2019-08-03T09:54:39Z" duration-ms="30916">
    <groups>
    </groups>
    <test started-at="2019-08-03T09:54:08Z" name="Test" finished-at="2019-08-03T09:54:39Z" duration-ms="30916">
      <class name="BasicTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:BasicTest@59717824]" started-at="2019-08-03T09:54:08Z" name="setup" finished-at="2019-08-03T09:54:18Z" duration-ms="9702" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="basicTest()[pri:0, instance:BasicTest@59717824]" started-at="2019-08-03T09:54:18Z" name="basicTest" finished-at="2019-08-03T09:54:30Z" duration-ms="12227" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at BasicTest.basicTest(BasicTest.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:835)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- basicTest -->
        <test-method is-config="true" signature="cleanup()[pri:0, instance:BasicTest@59717824]" started-at="2019-08-03T09:54:30Z" name="cleanup" finished-at="2019-08-03T09:54:39Z" duration-ms="8961" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
      </class> <!-- BasicTest -->
    </test> <!-- Test -->
  </suite> <!-- Guru99 Testing -->
</testng-results>
